Fix CFG directory.

diff --git a/tools-common b/tools-common
--- a/tools-common
+++ b/tools-common
@@ -1,5 +1,7 @@
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 export SRC=$(cd $DIR/../.. && pwd)
+export PROJECT_CFG="$(cd $SRC/config && pwd)"
+[ ! -d "$PROJECT_CFG" ] && echo "Missing project config directory. Exiting." 1>&2 && exit 1
 export CFG="$(cd $DIR/config-samples && pwd)"
 export php="/usr/bin/env php"
 export TOP_PID=$$
